
spring.datasource.url=${DB_URL:jdbc:postgresql://wt_projekt_db_user:WGlPBT5PZri13u5ZCBWtPiooBj0ddDlp@dpg-d7rg3ntckfvc73a1k30g-a.oregon-postgres.render.com/wt_projekt_db?sslmode=require}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect